#!/bin/bash

function createBadanPertahananNasional() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/badanpertahanannasional.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-badanpertahanannasional --tls.certfiles "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-badanpertahanannasional.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-badanpertahanannasional.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-badanpertahanannasional.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-badanpertahanannasional.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy badanpertahanannasional's CA cert to badanpertahanannasional's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem" "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/msp/tlscacerts/ca.crt"

  # Copy badanpertahanannasional's CA cert to badanpertahanannasional's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem" "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/tlsca/tlsca.badanpertahanannasional.example.com-cert.pem"

  # Copy badanpertahanannasional's CA cert to badanpertahanannasional's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem" "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/ca/ca.badanpertahanannasional.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-badanpertahanannasional --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-badanpertahanannasional --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-badanpertahanannasional --id.name badanpertahanannasionaladmin --id.secret badanpertahanannasionaladminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-badanpertahanannasional -M "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/peers/peer0.badanpertahanannasional.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/peers/peer0.badanpertahanannasional.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-badanpertahanannasional -M "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/peers/peer0.badanpertahanannasional.example.com/tls" --enrollment.profile tls --csr.hosts peer0.badanpertahanannasional.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/peers/peer0.badanpertahanannasional.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/peers/peer0.badanpertahanannasional.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/peers/peer0.badanpertahanannasional.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/peers/peer0.badanpertahanannasional.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/peers/peer0.badanpertahanannasional.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/peers/peer0.badanpertahanannasional.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-badanpertahanannasional -M "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/users/User1@badanpertahanannasional.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/users/User1@badanpertahanannasional.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://badanpertahanannasionaladmin:badanpertahanannasionaladminpw@localhost:7054 --caname ca-badanpertahanannasional -M "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/users/Admin@badanpertahanannasional.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/badanpertahanannasional/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/badanpertahanannasional.example.com/users/Admin@badanpertahanannasional.example.com/msp/config.yaml"
}

function createUser() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/user.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/user.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-user --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-user.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-user.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-user.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-user.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/user.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy user's CA cert to user's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/user.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/user/ca-cert.pem" "${PWD}/organizations/peerOrganizations/user.example.com/msp/tlscacerts/ca.crt"

  # Copy user's CA cert to user's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/user.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/user/ca-cert.pem" "${PWD}/organizations/peerOrganizations/user.example.com/tlsca/tlsca.user.example.com-cert.pem"

  # Copy user's CA cert to user's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/user.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/user/ca-cert.pem" "${PWD}/organizations/peerOrganizations/user.example.com/ca/ca.user.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-user --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-user --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-user --id.name useradmin --id.secret useradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.example.com/peers/peer0.user.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.example.com/peers/peer0.user.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.example.com/peers/peer0.user.example.com/tls" --enrollment.profile tls --csr.hosts peer0.user.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/user.example.com/peers/peer0.user.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/user.example.com/peers/peer0.user.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/user.example.com/peers/peer0.user.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/user.example.com/peers/peer0.user.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/user.example.com/peers/peer0.user.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/user.example.com/peers/peer0.user.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.example.com/users/User1@user.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.example.com/users/User1@user.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://useradmin:useradminpw@localhost:8054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.example.com/users/Admin@user.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.example.com/users/Admin@user.example.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls" --enrollment.profile tls --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
